# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/emdesigner',
                'doc_host': 'https://NaveenDeepak.github.io',
                'git_url': 'https://github.com/NaveenDeepak/emdesigner',
                'lib_path': 'emdesigner'},
  'syms': {'emdesigner.core': {'emdesigner.core.foo': ('core.html#foo', 'emdesigner/core.py')}}}
