# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "spm": "01_electricmachinepu.ipynb",
         "ipm": "01_electricmachinepu.ipynb",
         "Stator": "02_stator.ipynb",
         "Rotor": "03_rotor.ipynb",
         "transform": "04_dq.ipynb",
         "inv_transform": "04_dq.ipynb",
         "cogging": "05_cogging.ipynb"}

modules = ["core.py",
           "electricmachinepu.py",
           "stator.py",
           "rotor.py",
           "dq.py"]

doc_url = "https://NaveenDeepak.github.io/emdesigner/"

git_url = "https://github.com/NaveenDeepak/emdesigner/tree/master/"

def custom_doc_links(name): return None
