# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "spm": "01_electricmachinepu.ipynb",
         "ipm": "01_electricmachinepu.ipynb",
         "stator": "02_stator.ipynb"}

modules = ["core.py",
           "electricmachinepu.py",
           "stator.py",
           "rotor.py"]

doc_url = "https://NaveenDeepak.github.io/emdesigner/"

git_url = "https://github.com/NaveenDeepak/emdesigner/tree/master/"

def custom_doc_links(name): return None
