# AUTOGENERATED! DO NOT EDIT! File to edit: 05_cogging.ipynb (unless otherwise specified).

__all__ = ['cogging']

# Cell
import numpy as np
import matplotlib.pyplot as plt
from emdesigner import stator, rotor

# Cell
def cogging(s, r):
    Nc = np.lcm(s.Ns, r.Np)
    embrace_list = []
    embrace = 0
    j = 1
    while(embrace<1):
        embrace = round(j*r.Np/Nc,3)
        embrace_list.append(embrace)
        j += 1

    return embrace_list
