# AUTOGENERATED! DO NOT EDIT! File to edit: 01_electricmachinepu.ipynb (unless otherwise specified).

__all__ = ['spm', 'M1']

# Cell
import numpy as np
import matplotlib.pyplot as plt


# Cell
class spm():
    def __init__(self, lpu):
        self.lpu = lpu
        self.phi_m = np.sqrt(1-lpu**2)
        self.speed = []
        self.torque = []
        self.voltage = []
        self.current = []
        self.gamma = []
        self.power = []

    def motorprofile(self, gamma_limit = 85):
        gamma_deg = 0
        # constant torque region
        for o in np.arange(0,1.1,0.1):
            gamma = gamma_deg*np.pi/180
            v = o * np.sqrt( (self.phi_m - np.sin(gamma))**2 + (self.lpu * np.cos(gamma))**2 )
            t = self.phi_m * np.cos(gamma)
            p = t*o
            self.speed.append(o)
            self.voltage.append(v)
            self.gamma.append(gamma)
            self.torque.append(t)
            self.power.append(p)
        # constant power region
        for gamma_deg in range(1,85):
            gamma = gamma_deg*np.pi/180
            o = 1/np.sqrt( (self.phi_m - np.sin(gamma))**2 + (self.lpu * np.cos(gamma))**2 )
            t = self.phi_m * np.cos(gamma)
            p = t*o
            self.speed.append(o)
            self.voltage.append(v)
            self.gamma.append(gamma_deg)
            self.torque.append(t)
            self.power.append(p)

    def plot_profile(self):
        fig, axs = plt.subplots(3)
        fig.set_figheight(8)
        axs[0].plot(self.speed, self.torque)
        axs[0].set_title('torque vs speed')
        axs[1].plot(self.speed, self.power)
        axs[1].set_title('power vs speed')
        axs[2].plot(self.speed, self.gamma)
        axs[2].set_title('gamma vs speed')

        # Hide x labels and tick labels for top plots and y ticks for right plots.
        for ax in axs.flat:
            ax.label_outer()

        plt.tight_layout()
        plt.show()


# Cell
M1 = spm(0.6)
M1.motorprofile()
M1.plot_profile()