# AUTOGENERATED! DO NOT EDIT! File to edit: 03_rotor.ipynb (unless otherwise specified).

__all__ = ['rotor']

# Cell
import numpy as np
import matplotlib.pyplot as plt

# Cell
class rotor():
    def __init__(self, OD, Np, g, ID, magnet_pitch_f, magnet_thickness_f, len):
        self.OD = OD                        # rotor outer diameter
        self.Np = Np                        # number of poles
        self.topology = 'spm'               # rotor topology
        self.g = g                          # airgap
        self.ID = ID                        # rotor inner diameter/shaft diameter
        self.mag_pitch_f = magnet_pitch_f   # magnet pitch as a fraction of one pole angle
        self.mag_thickness_f = magnet_thickness_f # magnet thickness as a fraction of radial difference between OD and shaft
        self.len = len                      # rotor stack/magnet length along the radial direction
        self.core_area = 0
        self.magnet_area = 0

    def calc_area(self,):
        magnet_thickness = self.mag_thickness_f*0.5*(self.OD - self.ID)
        print('magnet thickness ', magnet_thickness)
        self.core_area = 10 #np.pi*0.25*((self.OD - 2*magnet_thickness)**2 - self.ID**2)
        self.magnet_area = 12 #(np.pi*0.25*(self.OD**2 - self.ID**2) - self.core_area)*self.mag_pitch_f

